## Arithmetic Operations

In [1]:
r = 1758
t = 0.2

In [2]:
total = r * (1 + t)
total

2109.6

In [3]:
2 != 3

True

In [6]:
(55>24) and (10<1)

False

### List

In [7]:
l = [10,20,30,40]

In [20]:
l = [10, 'test1234','mest', [40,10], 123, 8.4]

In [9]:
l[0] = 11

In [11]:
l

[11, 'test1234', 'mest', [40, 10], 123, 8, 4]

In [18]:
len(l[2])

4

In [21]:
len(l)

6

In [22]:
l.append(50)

In [23]:
l = ['data1.csv', 'data2.csv', 'data3.csv']

### Tuple

In [25]:
t = (10, 12, 13)

### Set

In [26]:
my_list = [1, 2, 3, 4, 6, 6, 6, 6, 6]

In [29]:
my_set = set(my_list)
new_l = list(my_set)
new_l

[1, 2, 3, 4, 6]

In [30]:
a = {1,2,3,4,5}
b = {4,5,6,7,8}

In [32]:
a.intersection(b)

{4, 5}

In [33]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8}

In [35]:
a.difference(b)

{1, 2, 3}

In [36]:
b.difference(a)

{6, 7, 8}

### Dictonary

In [3]:
# key value pairs
customers = {
             'Alice': 25, 
             'Bob': 30, 
             'Charlie': 35,
             'Charlie': 31,
             'Charlie': [32,2]
             }

In [4]:
customers

{'Alice': 25, 'Bob': 30, 'Charlie': [32, 2]}

In [5]:
customers['Alice'] = 30

In [6]:
customers

{'Alice': 30, 'Bob': 30, 'Charlie': [32, 2]}

In [7]:
customer = {'name': 'Alice', 'age': 30, 'city': 'New York'}
customer['State'] = 'NY'
customer['Segment'] = 'Premium'

In [8]:
customer1 = customer
customer

{'name': 'Alice',
 'age': 30,
 'city': 'New York',
 'State': 'NY',
 'Segment': 'Premium'}

In [10]:
# Bob
customer2 = {'name': 'Bob', 'age': 25, 'city': 'Los Angeles', 'State': 'CA', 'Segment': 'Standart'}

In [11]:
list_of_customers = [customer1, customer2]

In [12]:
list_of_customers

[{'name': 'Alice',
  'age': 30,
  'city': 'New York',
  'State': 'NY',
  'Segment': 'Premium'},
 {'name': 'Bob',
  'age': 25,
  'city': 'Los Angeles',
  'State': 'CA',
  'Segment': 'Standart'}]

In [13]:
list(list_of_customers[0].keys())

['name', 'age', 'city', 'State', 'Segment']

In [15]:
l = [10, 20, 30, 40]
d = {'keys', 'value'}

### Pandas

In [16]:
import pandas as pd

In [22]:
data = {'name': ['Alice', 'Bob', 'Charlie','David','Armen'], 
        'age': [30, 25, 28, 35, 42], 
        'city': ['New York', 'Los Angeles', 'Chicago', 'Boston', 'San Francisco'],
        'revenue': [10000, 15000, 12000, 20000, 18000],
        'segment': ['Premium', 'Premium', 'Premium', 'Standard', 'Premium'],}

In [23]:
df = pd.DataFrame(data)
df.head()

      name  age           city  revenue   segment
0    Alice   30       New York    10000   Premium
1      Bob   25    Los Angeles    15000   Premium
2  Charlie   28        Chicago    12000   Premium
3    David   35         Boston    20000  Standard
4    Armen   42  San Francisco    18000   Premium

In [24]:
l = [10,20,30,50]
l2 = [i**2 for i in l]

In [25]:
l2

[100, 400, 900, 2500]

In [26]:
df.loc[df["revenue"] > 12000,"segment"] = "High Revenue"

In [27]:
df.head()

      name  age           city  revenue       segment
0    Alice   30       New York    10000       Premium
1      Bob   25    Los Angeles    15000  High Revenue
2  Charlie   28        Chicago    12000       Premium
3    David   35         Boston    20000  High Revenue
4    Armen   42  San Francisco    18000  High Revenue

In [29]:
revenue = 99

if revenue > 100:
    print("High revenue")
    print(f"Because the revenue is: {revenue}")

else:
    print("Low Revenue")

print("Analysis complete")

Low Revenue
Analysis complete

In [31]:
revenue = 201

if revenue > 200:
    print(f"Very high revenue: {revenue}")
elif revenue > 100:
    print(f"High revenue: {revenue}")
elif revenue > 50:
    print(f"Medium revenue: {revenue}")
else:
    print(f"Low revenue: {revenue}")

Very high revenue: 201

In [32]:
b = 5
a = 6

In [34]:
a = b
a

5

In [37]:
a != b

False

In [38]:
revenue = 150
is_active = False

if revenue > 100 or is_active:
    print("Target customer")

Target customer

In [39]:
if is_active:
    print("Customer is active")

In [40]:
a = 6
b = 5

In [41]:
a = a + b
a

11

In [42]:
c = a
a = b
b = c

In [43]:
a = a + b

In [44]:
b = a - b
a = a - b

In [45]:
a

11

In [46]:
b

5

In [47]:
print(f"a is equal to: {a} \n b is equal to: {b}")

a is equal to: 11
 b is equal to: 5

In [48]:
print(revenue)
if revenue == 150:
    print("Equal")

150
Equal

In [49]:
a = 5; b = 10; c = 15

In [50]:
if revenue > 100:
    print("High")

High

In [51]:
list_of_data_sources = ['data1.csv', 'data2.csv', 'data3.csv']

In [52]:
for i in list_of_data_sources:
    print(f'then name of current data source is: {i}')

print("Exit loop")

then name of current data source is: data1.csv
then name of current data source is: data2.csv
then name of current data source is: data3.csv
Exit loop

In [53]:
number_of_clicks = 0 

for i in range(100):
    number_of_clicks = i + 1

number_of_clicks

100

In [54]:
sales = [100, 200, 150, 50]

for value in sales:
    if value > 120:
        print("High sale:", value)
    else:
        print("Low sale:", value)

Low sale: 100
High sale: 200
High sale: 150
Low sale: 50

In [55]:
customer = {
    "name": "Anna",
    "revenue": 150,
    "city": "Yerevan"
}

In [56]:
customer.keys()
customer['name']

'Anna'

In [57]:
customer['city']

'Yerevan'

In [58]:
customer['revenue']

150

In [60]:
customer = {
    "name": ["Anna", "Gagik"],
    "revenue": [150, 200],
    "city": ["Yerevan"]
}

In [61]:
customer

{'name': ['Anna', 'Gagik'], 'revenue': [150, 200], 'city': ['Yerevan']}

In [62]:
customer.items()

dict_items([('name', ['Anna', 'Gagik']), ('revenue', [150, 200]), ('city', ['Yerevan'])])

In [63]:
for key, value in customer.items():
    print(key)
    print(key, ":", customer[key][1])

name
name : Gagik
revenue
revenue : 200
city

IndexError: list index out of range

In [64]:
l = [10,20,30,40,50]
for i in l[3:]:
    print(i)

40
50

In [65]:
l[:3]

[10, 20, 30]