## Arithmetic Operations

In [121]:
r = 1758
t = 0.2

In [122]:
total = r * (1 + t)
total

2109.6

In [123]:
2 != 3

True

In [124]:
(55>24) and (10<1)

False

### List

In [125]:
l = [10,20,30,40]

In [126]:
l = [10, 'test1234','mest', [40,10], 123, 8.4]

In [127]:
l[0] = 11

In [128]:
l

[11, 'test1234', 'mest', [40, 10], 123, 8.4]

In [129]:
len(l[2])

4

In [130]:
len(l)

6

In [131]:
l.append(50)

In [132]:
l = ['data1.csv', 'data2.csv', 'data3.csv']

### Tuple

In [133]:
t = (10, 12, 13)

### Set

In [134]:
my_list = [1, 2, 3, 4, 6, 6, 6, 6, 6]

In [135]:
my_set = set(my_list)
new_l = list(my_set)
new_l

[1, 2, 3, 4, 6]

In [136]:
a = {1,2,3,4,5}
b = {4,5,6,7,8}

In [137]:
a.intersection(b)

{4, 5}

In [138]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8}

In [139]:
a.difference(b)

{1, 2, 3}

In [140]:
b.difference(a)

{6, 7, 8}

### Dictonary

In [141]:
# key value pairs
customers = {
             'Alice': 25, 
             'Bob': 30, 
             'Charlie': 35,
             'Charlie': 31,
             'Charlie': [32,2]
             }

In [142]:
customers

{'Alice': 25, 'Bob': 30, 'Charlie': [32, 2]}

In [143]:
customers['Alice'] = 30

In [144]:
customers

{'Alice': 30, 'Bob': 30, 'Charlie': [32, 2]}

In [145]:
customer = {'name': 'Alice', 'age': 30, 'city': 'New York'}
customer['State'] = 'NY'
customer['Segment'] = 'Premium'

In [146]:
customer1 = customer
customer

{'name': 'Alice',
 'age': 30,
 'city': 'New York',
 'State': 'NY',
 'Segment': 'Premium'}

In [147]:
# Bob
customer2 = {'name': 'Bob', 'age': 25, 'city': 'Los Angeles', 'State': 'CA', 'Segment': 'Standart'}

In [148]:
list_of_customers = [customer1, customer2]

In [149]:
list_of_customers

[{'name': 'Alice',
  'age': 30,
  'city': 'New York',
  'State': 'NY',
  'Segment': 'Premium'},
 {'name': 'Bob',
  'age': 25,
  'city': 'Los Angeles',
  'State': 'CA',
  'Segment': 'Standart'}]

In [150]:
list(list_of_customers[0].keys())

['name', 'age', 'city', 'State', 'Segment']

In [151]:
l = [10, 20, 30, 40]
d = {'keys', 'value'}

### Pandas

In [152]:
import pandas as pd

In [153]:
data = {'name': ['Alice', 'Bob', 'Charlie','David','Armen'], 
        'age': [30, 25, 28, 35, 42], 
        'city': ['New York', 'Los Angeles', 'Chicago', 'Boston', 'San Francisco'],
        'revenue': [10000, 15000, 12000, 20000, 18000],
        'segment': ['Premium', 'Premium', 'Premium', 'Standard', 'Premium'],}

In [154]:
df = pd.DataFrame(data)
df.head()

      name  age           city  revenue   segment
0    Alice   30       New York    10000   Premium
1      Bob   25    Los Angeles    15000   Premium
2  Charlie   28        Chicago    12000   Premium
3    David   35         Boston    20000  Standard
4    Armen   42  San Francisco    18000   Premium

In [155]:
l = [10,20,30,50]
l2 = [i**2 for i in l]

In [156]:
l2

[100, 400, 900, 2500]

In [157]:
df.loc[df["revenue"] > 12000,"segment"] = "High Revenue"

In [158]:
df.head()

      name  age           city  revenue       segment
0    Alice   30       New York    10000       Premium
1      Bob   25    Los Angeles    15000  High Revenue
2  Charlie   28        Chicago    12000       Premium
3    David   35         Boston    20000  High Revenue
4    Armen   42  San Francisco    18000  High Revenue

### If Statment

In [159]:
revenue = 99

if revenue > 100:
    print("High revenue")
    print(f"Because the revenue is: {revenue}")

else:
    print("Low Revenue")

print("Analysis complete")

Low Revenue
Analysis complete

In [160]:
revenue = 201

if revenue > 200:
    print(f"Very high revenue: {revenue}")
elif revenue > 100:
    print(f"High revenue: {revenue}")
elif revenue > 50:
    print(f"Medium revenue: {revenue}")
else:
    print(f"Low revenue: {revenue}")

Very high revenue: 201

In [161]:
b = 5
a = 6

In [162]:
a = b
a

5

### Boolean

In [163]:
a != b

False

In [164]:
revenue = 150
is_active = False

if revenue > 100 or is_active:
    print("Target customer")

Target customer

In [165]:
if is_active:
    print("Customer is active")

### Loops

In [166]:
'(V V V V V V V V V)'

'(V V V V V V V V V)'

In [167]:
f"({df.shape[1]*'V$ '})"

'(V$ V$ V$ V$ V$ )'

In [168]:
 101*'V'

'VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV'

In [169]:
sales = [10,20,30,40,50,77,0,113]

sales[0] = sales[0]*2
sales[1] = sales[1]*2
sales[2] = sales[2]*2
sales[3] = sales[3]*2
sales[4] = sales[4]*2

In [170]:
for i in range(11,100,11):
    print(i)

11
22
33
44
55
66
77
88
99

In [171]:
sales

[20, 40, 60, 80, 100, 77, 0, 113]

In [172]:
len(sales)

for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [173]:
for i in range(len(sales)):

    sales[i] = sales[i]*2

sales

[40, 80, 120, 160, 200, 154, 0, 226]

In [174]:
sales

total = 100

for i in sales:
    print(f'Total before {total}')
    print(16*'^')
    print(16*' ')
    print(4*' [] ')
    total = total + i
    print(16*'_')
    print(f'Total after{total}')

Total before 100
^^^^^^^^^^^^^^^^

 []  []  []  []
________________
Total after140
Total before 140
^^^^^^^^^^^^^^^^

 []  []  []  []
________________
Total after220
Total before 220
^^^^^^^^^^^^^^^^

 []  []  []  []
________________
Total after340
Total before 340
^^^^^^^^^^^^^^^^

 []  []  []  []
________________
Total after500
Total before 500
^^^^^^^^^^^^^^^^

 []  []  []  []
________________
Total after700
Total before 700
^^^^^^^^^^^^^^^^

 []  []  []  []
________________
Total after854
Total before 854
^^^^^^^^^^^^^^^^

 []  []  []  []
________________
Total after854
Total before 854
^^^^^^^^^^^^^^^^

 []  []  []  []
________________
Total after1080

In [175]:
sales
sales_new = []
total = 0

for i in sales:
    sales_new.append(i*2)

print(sales)
print(sales_new)

[40, 80, 120, 160, 200, 154, 0, 226]
[80, 160, 240, 320, 400, 308, 0, 452]

In [176]:
loser = []
sales_new = []
for i in sales:
    sales_new.append(i*2)
else:
    loser.append(i)

print(loser)
print(sales_new)

[226]
[80, 160, 240, 320, 400, 308, 0, 452]

In [177]:
customer = {
    "data_name1": "data_url1",
    "data_name2": "data_url2",
    "data_name3": "data_url3",
    "data_name4": "data_url4",

}

for key in customer.keys():
    print(f'Download <{customer[key]}> and save in some folder and name it as <{key}>.csv')

Download <data_url1> and save in some folder and name it as <data_name1>.csv
Download <data_url2> and save in some folder and name it as <data_name2>.csv
Download <data_url3> and save in some folder and name it as <data_name3>.csv
Download <data_url4> and save in some folder and name it as <data_name4>.csv

In [178]:
for key, value in customer.items():
    print(f'Download <{value}> and save in some folder and name it as <{key}>.csv')

Download <data_url1> and save in some folder and name it as <data_name1>.csv
Download <data_url2> and save in some folder and name it as <data_name2>.csv
Download <data_url3> and save in some folder and name it as <data_name3>.csv
Download <data_url4> and save in some folder and name it as <data_name4>.csv

In [179]:
for i in range(3):
    for j in range(2):
        print("i =", i, ", j =", j)

i = 0 , j = 0
i = 0 , j = 1
i = 1 , j = 0
i = 1 , j = 1
i = 2 , j = 0
i = 2 , j = 1

### List Comprehentions

In [180]:
sales

[40, 80, 120, 160, 200, 154, 0, 226]

In [181]:
new_sales = [i*2 for i in sales]
new_sales

[80, 160, 240, 320, 400, 308, 0, 452]

In [201]:
v = 'vahe'
v_l = [i for i in a]
v_l

['v', 'a', 'h', 'e']

In [183]:
l = [1,2,3,0,5]

l_1 = [i for i in l if i >0]
l_0 = [i for i in l if i==0]

l_1

[1, 2, 3, 5]

In [184]:
["SuperMan" if value>2 else "Joker" for value in l]

['Joker', 'Joker', 'SuperMan', 'Joker', 'SuperMan']

In [185]:
" (rich) ".join(a_l)

'v (rich) a (rich) h (rich) e'

In [205]:
g = 3

In [206]:
c = g
g = b
b = c

In [208]:
g = g + b

In [209]:
b = g - b
g = g - b

In [215]:
print(f" g is equal to: {g}  \n b is equal to: {b}")

 g is equal to: 3
 b is equal to: 5

In [224]:
print(revenue)
if revenue == 15:
    print("Equal")
else: print("Cancle")

150
Cancle

In [225]:
a = 5; b = 10; c = 15

In [229]:
if revenue > 1000:
    print("High")
else: print("Low")

Low

In [230]:
list_of_data_sources = ['data1.csv', 'data2.csv', 'data3.csv']

In [234]:
for i in list_of_data_sources:
    print(f'the correct data source name is: {i}')

print("Exit loop")

the correct data source name is: data1.csv
the correct data source name is: data2.csv
the correct data source name is: data3.csv
Exit loop

In [239]:
number_of_clicks = 0

for i in range(100):
    number_of_clicks += 1

In [240]:
number_of_clicks

100

In [242]:
sales = [10, 20, 30, 40, 5]

for value in sales:
    if value > 12:
        print("High sale:", value)
    else:
        print("Low sale:", value)

Low sale: 10
High sale: 20
High sale: 30
High sale: 40
Low sale: 5

In [250]:
customer = {
    "name": " Anna",
    "revenue": 150000,
    "city": "Hrazdan"
}

In [251]:
customer['name']

' Anna'

In [252]:
customer['city']

'Hrazdan'

In [253]:
customer.keys()

dict_keys(['name', 'revenue', 'city'])

In [254]:
customer['revenue']

150000

In [256]:
customer = {
    "name": ["Vahe", "Arman"],
    "revenue": [600000, 700000],
    "city": ["Hrazdan", "Hrazdan"]
}

customer

{'name': ['Vahe', 'Arman'],
 'revenue': [600000, 700000],
 'city': ['Hrazdan', 'Hrazdan']}

In [ ]:
customer.items()

SyntaxError: unexpected character after line continuation character (2817969193.py, line 1)

In [263]:
for key, value in customer.items():
    print(key)
    print(key,":", customer[key][1])

name
name : Arman
revenue
revenue : 700000
city
city : Hrazdan

In [266]:
l = [10,20,30,40,50]
for i in l[2:]:
    print(i)

30
40
50

In [267]:
l[:3]

[10, 20, 30]