## Import Packages

In [1]:
import pandas as pd
from os.path import join

## Functions

### Simple Function

In [2]:
def add_numbers(a: float, b: float) -> float:
    """
    Add two numeric values and return their sum.

    This function takes two numbers, adds them together, and returns the result.
    Although the parameters are annotated as floats, integers can also be passed
    because they are compatible with numeric addition in Python.

    Parameters
    ----------
    a : float
        The first number to add.
    b : float
        The second number to add.
        
    Returns
    -------
    float
        The sum of `a` and `b`.
        
    Examples
    --------
    >>> add_numbers(2, 3)
    5
    """      
    c = a + b
    
    return c

In [3]:
URL = "https://github.com/hovhannisyan91/sql-analytics-portfolio/tree/main/data"

join(URL,'public_schema', 'customers.csv')

'https://github.com/hovhannisyan91/sql-analytics-portfolio/tree/main/data\\public_schema\\customers.csv'

### CSV Dowloader 1

In [4]:
csv_files = ['customers', 'orders']

def csv_dowloader(csv_files:list, source:str, destination: str,):
    for i in csv_files:
        print(f"trying to read: {i}")
        print(f"source: {source}")
        print(f"destination: {destination}")
        
        df = pd.read_csv(f"{join(source,i)}.csv")
        print(f"{i} shape: {df.shape}")
        df.to_csv(join(destination,f"{i}.csv"))
        print(10*"=")
        
    return 'Okay'

In [5]:
URL = 'https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/'
DESTINATION = 'C:\\aca\\sql-analytics-portfolio\\Data\\public_schema'
DESTINATION = '../data/public'
csv_dowloader(csv_files=csv_files, source=URL, destination=DESTINATION)

trying to read: customers
source: https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/
destination: ../data/public
customers shape: (2000, 5)
==========
trying to read: orders
source: https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/
destination: ../data/public
orders shape: (200, 5)
==========

'Okay'

### CSV Dowloader 2

In [6]:
def csv_dowloader(csv_files: list, source:str, destination:str, file_type: str = "csv"):
    for i in csv_files:
        print(f"trying to read: {i}")
        print(f"source: {source}")
        print(f"destination: {destination}")
        
        df = pd.read_csv(f"{join(source,i)}.csv")
        print(f"{i} shape: {df.shape}")
        
        file_name = join(destination, f"{i}.{file_type}")
        print(file_name)
        if file_type == 'xlsx':
            df.to_excel(file_name, index=False)
        elif file_type == 'parquet':
            df.to_parquet(file_name, index=False)
        else:
            df.to_csv(file_name, index=False)
        print(30*"=")
        
    return 'Okay'

In [7]:
URL = "https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/"
# DESTINATION = 'C:\\aca\\sql-analytics-portfolio\\Data\\public_schema'
DESTINATION = '../data/public'
csv_dowloader(csv_files= csv_files, source= URL, destination= DESTINATION, file_type= 'xlsx')

trying to read: customers
source: https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/
destination: ../data/public
customers shape: (2000, 5)
../data/public\customers.xlsx
==============================
trying to read: orders
source: https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/
destination: ../data/public
orders shape: (200, 5)
../data/public\orders.xlsx
==============================

'Okay'

### CSV Dowloader Import

In [8]:
from utils import csv_dowloader

In [9]:
csv_dowloader

In [12]:
customer_df, orders_df = csv_dowloader(csv_files= csv_files,
                                   source=URL,
                                   destination=DESTINATION,
                                   type='parquet')

trying to read: customers
source: https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/
destination: ../data/public
customers shape: (2000, 5)
appending to the list:
../data/public\customers.parquet
==========
trying to read: orders
source: https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/
destination: ../data/public
orders shape: (200, 5)
appending to the list:
../data/public\orders.parquet
==========

In [13]:
orders_df.head()

   order_id                  order_date  year  quarter     month
0         1  2020-04-14 19:59:10.340663  2020        2     April
1         2  2022-06-19 19:49:00.777498  2022        2      June
2         3  2023-04-22 10:34:29.264475  2023        2     April
3         4  2020-06-05 17:30:50.324055  2020        2      June
4         5  2022-11-08 07:38:02.311339  2022        4  November

In [14]:
customer_df.head()

,customer_id,customer_name,address,city,zip_code
0,1,Emily White,14752 Jones Ways,South Sean,59444
1,2,Chad Mcclain,7292 Anthony Lodge,Priceland,37902
2,3,Peter Holmes,682 Cook Corner Suite 430,Gayfurt,77812
3,4,Kathryn Cunningham,58670 Trujillo Ports,Tylerland,27254
4,5,Catherine Johnson,4617 Gray Cape,Reginaldhaven,66469

### With Pandas

In [16]:
def score_label(score):
    if score >= 90:
        return "Excellent"
    elif score >= 70:
        return "Good"
    elif score >= 50:
        return "Pass"
    else:
        return "Fail"
    
score_label(53)

'Pass'

#### List Comperehension

In [17]:
df_scores = pd.DataFrame({
    "student": ["Vahe", "An", "Hak", "Tony"],
    "score": [77, 90, 89, 65,]
})

df_scores

  student  score
0    Vahe     77
1      An     90
2     Hak     89
3    Tony     65

In [18]:
df_scores['label_lc'] = [score_label(i) for i in df_scores['score']]
df_scores

  student  score   label_lc
0    Vahe     77       Good
1      An     90  Excellent
2     Hak     89       Good
3    Tony     65       Pass

#### Apply

In [19]:
df_scores['label_apply'] = df_scores['score'].apply(score_label)
df_scores

  student  score   label_lc label_apply
0    Vahe     77       Good        Good
1      An     90  Excellent   Excellent
2     Hak     89       Good        Good
3    Tony     65       Pass        Pass

In [20]:
df_products_dummy = pd.DataFrame({
    "product": ["Milk", "Bread", "Juice", "Cheese", "Steak"],
    "price": [400, 250, 800, 1500, 2800]
})

df_products_dummy

  product  price
0    Milk    400
1   Bread    250
2   Juice    800
3  Cheese   1500
4   Steak   2800

In [21]:
def classify_price(price: float, low:int=500, high:int=2000):
    if price <= low:
        return "Low-range product"
    elif price <= high:
        return "Mid-range product"
    else:
        return "High-range product"
    
classify_price(2600)

'High-range product'

In [22]:
df_products_dummy['classify_price'] = df_products_dummy['price'].apply(classify_price)

In [23]:
df_products_dummy

  product  price      classify_price
0    Milk    400   Low-range product
1   Bread    250   Low-range product
2   Juice    800   Mid-range product
3  Cheese   1500   Mid-range product
4   Steak   2800  High-range product

In [24]:
def income_band(income, low=30000, high=70000):
    if income < low:
        return "Low income"
    elif income < high:
        return "Middle income"
    else:
        return "High income"

In [28]:
df_customers_dummy = pd.DataFrame({
    "customer": ["A", "B", "C", "D"],
    "age": [33, 32, 19, 22],
    "income": [18000, 50000, 90000, 30000]
})

df_customers_dummy

  customer  age  income
0        A   33   18000
1        B   32   50000
2        C   19   90000
3        D   22   30000

In [29]:
df_customers_dummy["income_group"] = df_customers_dummy["income"].apply(income_band)
df_customers_dummy

  customer  age  income   income_group
0        A   33   18000     Low income
1        B   32   50000  Middle income
2        C   19   90000    High income
3        D   22   30000  Middle income

In [33]:
df_customers_dummy["income_group"] = (df_customers_dummy["income"]
                                      .apply(income_band,
                                             low = 40000,
                                             high = 90000))

df_customers_dummy

  customer  age  income   income_group
0        A   33   18000     Low income
1        B   32   50000  Middle income
2        C   19   90000    High income
3        D   22   30000     Low income

In [34]:
df_customers_dummy[['income', 'income_group']].groupby('income_group').mean()

                income
income_group
High income    90000.0
Low income     24000.0
Middle income  50000.0

In [ ]:
df_scores["pass_flag"] = (df_scores["score"]
                          .apply(lambda x: "Pass" if x >= 50 else "Fail"))

In [40]:
df_scores['test'] = df_customers_dummy['age']+df_scores['score']
df_scores

  student  score   label_lc label_apply pass_flag  test
0    Vahe     77       Good        Good      Pass   110
1      An     90  Excellent   Excellent      Pass   122
2     Hak     89       Good        Good      Pass   108
3    Tony     65       Pass        Pass      Pass    87