## Loading Packages

In [26]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

## Importing Dataframes

In [36]:
df_orders = pd.read_csv('../data/raw/orders.csv')
print(df_orders.shape)
df_orders.head()

(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [10]:
df_orders['eval_set'].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [11]:
df_orders_train = df_orders[df_orders['eval_set'] == 'train']
print(df_orders_train.shape)
df_orders_train.head()

df_orders_train.to_csv('../data/processed/orders_train.csv', index=False)

(131209, 7)

In [12]:
del df_orders

In [13]:
df_products = pd.read_csv('../data/raw/products.csv')
print(df_products.shape)
df_products.head()

(49693, 5)

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [14]:
# df_customers = pd.read_csv('../data/raw/customers.csv')

In [15]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.shape)
df_departments.head()

(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [16]:
df_aisales = pd.read_csv('../data/raw/aisles.csv')
print(df_aisales.shape)
df_aisales.head()

(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [18]:
# df_states = pd.read_csv('../data/raw/states,csv')

In [20]:
df_order_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_order_products_train.shape)
df_order_products_train.head()

(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

## Explore

### Orders

In [32]:
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [23]:
df_orders_train.info()

<class 'pandas.DataFrame'>
Index: 131209 entries, 10 to 3421082
Data columns (total 7 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                131209 non-null  int64
 1   user_id                 131209 non-null  int64
 2   eval_set                131209 non-null  str
 3   order_number            131209 non-null  int64
 4   order_dow               131209 non-null  int64
 5   order_hour_of_day       131209 non-null  int64
 6   days_since_prior_order  131209 non-null  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 8.0 MB

In [27]:
columns_to_explore = ['order_dow', 'order_hour_of_day', 'days_since_prior_order']

df_orders_train[columns_to_explore].describe()

       order_dow  order_hour_of_day  days_since_prior_order
count 131,209.00         131,209.00              131,209.00
mean        2.77              13.58                   17.05
std         2.12               4.22                   10.68
min         0.00               0.00                    0.00
25%         1.00              10.00                    7.00
50%         3.00              14.00                   15.00
75%         5.00              17.00                   30.00
max         6.00              23.00                   30.00

In [28]:
df_orders_train.isna().sum()

order_id                  0
user_id                   0
eval_set                  0
order_number              0
order_dow                 0
order_hour_of_day         0
days_since_prior_order    0
dtype: int64

In [30]:
df_orders_train['order_id'].nunique()

131209

In [33]:
df_orders_train['user_id'].nunique()

131209

In [37]:
df_orders['order_id'].nunique()

3421083

In [38]:
df_orders['user_id'].nunique()

206209

In [40]:
df_orders['eval_set'].value_counts(normalize=True)

eval_set
prior   0.94
train   0.04
test    0.02
Name: proportion, dtype: float64

In [41]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [42]:
df_orders['order_dow'].value_counts().sort_index()

order_dow
0    600905
1    587478
2    467260
3    436972
4    426339
5    453368
6    448761
Name: count, dtype: int64

In [43]:
df_orders['order_hour_of_day'].value_counts().sort_index()

order_hour_of_day
0      22758
1      12398
2       7539
3       5474
4       5527
5       9569
6      30529
7      91868
8     178201
9     257812
10    288418
11    284728
12    272841
13    277999
14    283042
15    283639
16    272553
17    228795
18    182912
19    140569
20    104292
21     78109
22     61468
23     40043
Name: count, dtype: int64

In [44]:
df_orders['order_hour_of_day'].between(0,23).all()

np.True_

In [48]:
df_orders['order_dow'].between(0,6).all()

np.True_

In [50]:
# high_sales = [value for value in sales if value > 120]

In [ ]:
# ValueError: Length of values (2232700) does not match length of index (3421083)

In [ ]:
# "High" if value > 120 else "Low"

In [55]:
df_orders['Weekend'] = ['Weekend' if i in [1,5] else 'Workday' for i in df_orders['order_dow']]
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,Weekend
0,2539329,1,prior,1,2,8,NaN,Workday
1,2398795,1,prior,2,3,7,15.00,Workday
2,473747,1,prior,3,3,12,21.00,Workday
3,2254736,1,prior,4,4,7,29.00,Workday
4,431534,1,prior,5,4,15,28.00,Workday

In [57]:
df_orders['Weekend'].value_counts(normalize=True)

Weekend
Workday   0.70
Weekend   0.30
Name: proportion, dtype: float64

### Customers

In [58]:
# df_customers.head()

In [59]:
# df_customers['Gender'].value.counts(normalize=True)

In [61]:
# df_customers[['n_depends','fam_status']].value_counts(normalize=True)

In [62]:
# df_customers[['Age,'income']].describe().drop(['count'])

### Products_Train

In [63]:
df_order_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [66]:
df_order_products_train.shape

(1384617, 4)

In [68]:
df_products[df_products['product_id']==33333]

       product_id   product_name  aisle_id  department_id  prices
33335       33333  Harvest Blend       125             19    1.90

In [69]:
df_order_products_train[['product_id', 'add_to_cart_order']].value_counts()

product_id  add_to_cart_order
24852       1                    4605
13176       1                    3889
24852       2                    3199
13176       2                    2867
24852       3                    2255
                                 ...
7615        28                      1
40800       1                       1
33424       3                       1
16475       4                       1
6858        5                       1
Name: count, Length: 316364, dtype: int64

In [74]:
basket_size = len(df_order_products_train)/df_order_products_train['order_id'].nunique()
print('Averager Market Basket:',basket_size)

Averager Market Basket: 10.552759338155157

In [75]:
df_order_products_train['product_id'].nunique()

39123

In [76]:
df_order_products_train['reordered'].value_counts(normalize=True)

reordered
1   0.60
0   0.40
Name: proportion, dtype: float64

### Products

In [77]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [78]:
df_products['product_id'].nunique()

49686

In [79]:
df_products['aisle_id'].nunique()

134

In [81]:
df_products['prices'].describe()

count   49,693.00
mean         9.99
std        453.52
min          1.00
25%          4.10
50%          7.10
75%         11.20
max     99,999.00
Name: prices, dtype: float64

In [82]:
df_departments

    department_id       department
0               1           frozen
1               2            other
2               3           bakery
3               4          produce
4               5          alcohol
5               6    international
6               7        beverages
7               8             pets
8               9  dry goods pasta
9              10             bulk
10             11    personal care
11             12     meat seafood
12             13           pantry
13             14        breakfast
14             15     canned goods
15             16       dairy eggs
16             17        household
17             18           babies
18             19           snacks
19             20             deli
20             21          missing

## Merge

In [84]:
# new_df = pd.merge(left_df,right_df, on = 'id', how = 'left')

In [87]:
df_products.head()
df_departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [91]:
df_products_departments = pd.merge(
    df_products, 
    df_departments,
    on = 'department_id',
    how = 'left', 
    indicator = True)

df_products_departments.head(20)

,product_id,product_name,aisle_id,department_id,prices,department,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks,both
1,2,All-Seasons Salt,104,13,9.30,pantry,both
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages,both
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen,both
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry,both
5,6,Dry Nose Oil,11,11,2.60,personal care,both
6,7,Pure Coconut Water With Orange,98,7,4.40,beverages,both
7,8,Cut Russet Potatoes Steam N' Mash,116,1,1.10,frozen,both
8,9,Light Strawberry Blueberry Yogurt,120,16,7.00,dairy eggs,both
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7,8.40,beverages,both
10,11,Peach Mango Juice,31,7,2.80,beverages,both
11,12,Chocolate Fudge Layer Cake,119,1,9.40,frozen,both
12,13,Saline Nasal Mist,11,11,1.10,personal care,both
13,14,Fresh Scent Dishwasher Cleaner,74,17,6.50,household,both
14,15,Overnight Diapers Size 6,56,18,11.20,babies,both
15,16,Mint Chocolate Flavored Syrup,103,19,5.20,snacks,both
16,17,Rendered Duck Fat,35,12,17.10,meat seafood,both
17,18,Pizza for One Suprema Frozen Pizza,79,1,10.60,frozen,both
18,19,Gluten Free Quinoa Three Cheese & Mushroom Blend,63,9,12.00,dry goods pasta,both
19,20,Pomegranate Cranberry & Aloe Vera Enrich Drink,98,7,6.00,beverages,both

In [92]:
df_products_departments.dtypes

product_id          int64
product_name          str
aisle_id            int64
department_id       int64
prices            float64
department            str
_merge           category
dtype: object

In [93]:
df_products_departments['_merge'].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64