# Dates

## Import Packages

In [30]:
import pandas as pd
from datetime import datetime, date, timedelta

## Datetime

In [2]:
simple_date = date(2024, 7, 1)
simple_date

datetime.date(2024, 7, 1)

In [3]:
simple_date = date(year = 2026, day = 22, month = 5)

simple_date

datetime.date(2026, 5, 22)

In [4]:
simple_date.month
simple_date.day
# simple_date.year

22

In [5]:
if simple_date.day>15:
    print('Ամիսը կիսվավ')
else:
    print("Ամիսը նոր է սկսվել")

Ամիսը կիսվավ

In [6]:
if date.today().day>15:
    print('Ամիսը կիսվավ')
else:
    print("Ամիսը նոր է սկսվել")

Ամիսը նոր է սկսվել

In [7]:
"""
SQL
- campaign_id incremental
- campaign_name 
- campaign_descrpiton
- start_date
- end_date
"""

def create_campaign():
    # TODO:
    pass

campaign_day = date.today()

In [8]:
datetime.now()

datetime.datetime(2026, 5, 14, 1, 36, 49, 840710)

In [9]:
dt = datetime(2026,5,22,12,12,5)

In [10]:
print(f"Year: {dt.year}")
print(f"Month: {dt.month}")
print(f"Day: {dt.day}")
print(f"Hour: {dt.hour}")
print(f"Minute: {dt.minute}")
print(f"Second: {dt.second}")

Year: 2026
Month: 5
Day: 22
Hour: 12
Minute: 12
Second: 5

In [11]:
dt.strftime("%B/%y/%d/%H")

'May/26/22/12'

In [12]:
mydate = "2024-07-01"
type(mydate)

str

In [14]:
dt = datetime.strptime("2024-07-01", "%Y-%d-%m")
dt

datetime.datetime(2024, 1, 7, 0, 0)

In [15]:
start = date(2024, 7, 1)
end = date(2024, 7, 15)
delta = end - start
type(delta)

datetime.timedelta

In [16]:
print(type(delta.days))
delta.days

<class 'int'>

14

In [17]:
def my_timedelta(years:int = 0, month:int = 0):
    my_date = timedelta(days=365 * years)+timedelta(days= 30*month)
    return my_date

In [18]:
years = 2

start + timedelta(days=365 * years)

datetime.date(2026, 7, 1)

In [19]:
df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates.to_csv('test.csv', index=False)

In [20]:
df_dates = pd.read_csv('test.csv',
                       parse_dates=['signup_date', 'last_purchase'])

df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), int64(1)
memory usage: 252.0 bytes

In [21]:
df_dates['new_signup_date'] = [(i, "%Y-%m-%d") for i in df_dates['signup_date']]

In [22]:
df_dates['new_day'] = df_dates['signup_date'] + pd.Timedelta(days=1)
print(df_dates[['signup_date', 'new_day']].head())

  signup_date    new_day
0  2024-01-15 2024-01-16
1  2024-02-20 2024-02-21
2  2024-03-05 2024-03-06
3  2024-03-18 2024-03-19
4  2024-04-10 2024-04-11

In [23]:
df_dates.head()

,customer_id,signup_date,last_purchase,new_signup_date,new_day
0,101,2024-01-15,2024-06-01,"(2024-01-15 00:00:00, %Y-%m-%d)",2024-01-16
1,102,2024-02-20,2024-06-15,"(2024-02-20 00:00:00, %Y-%m-%d)",2024-02-21
2,103,2024-03-05,2024-07-01,"(2024-03-05 00:00:00, %Y-%m-%d)",2024-03-06
3,104,2024-03-18,2024-07-08,"(2024-03-18 00:00:00, %Y-%m-%d)",2024-03-19
4,105,2024-04-10,2024-07-12,"(2024-04-10 00:00:00, %Y-%m-%d)",2024-04-11

In [24]:
df_dates.drop(columns='new_signup_date', inplace=True)

In [25]:
(df_dates["signup_date"].dt.day_of_week >= 5).astype(int)

0    0
1    0
2    0
3    0
4    0
Name: signup_date, dtype: int64

In [ ]:
df_dates["signup_date_don"] = df_dates["signup_date"].dt.day_name()
df_dates["signup_date_dow"] = df_dates["signup_date"].dt.day_of_week
df_dates["signup_date_dm"] = df_dates["signup_date"].dt.daysinmonth

df_dates

,customer_id,signup_date,last_purchase,new_day,signup-date-don,signup_date_dow,signup_date_dm,signup-date_don,signup_date_don,last_purchase_dow,last_purchase_doy,signup_date_doy
0,101,2024-01-15,2024-06-01,2024-01-16,Monday,0,31,Monday,Monday,5,153,Monday
1,102,2024-02-20,2024-06-15,2024-02-21,Tuesday,1,29,Tuesday,Tuesday,5,167,Tuesday
2,103,2024-03-05,2024-07-01,2024-03-06,Tuesday,1,31,Tuesday,Tuesday,0,183,Tuesday
3,104,2024-03-18,2024-07-08,2024-03-19,Monday,0,31,Monday,Monday,0,190,Monday
4,105,2024-04-10,2024-07-12,2024-04-11,Wednesday,2,30,Wednesday,Wednesday,4,194,Wednesday

In [35]:
pd.concat([df_dates, pd.get_dummies(df_dates["signup_date_don"], drop_first=True)], axis=1)

,customer_id,signup_date,last_purchase,new_day,signup-date-don,signup_date_dow,signup_date_dm,signup-date_don,signup_date_don,Tuesday,Wednesday
0,101,2024-01-15,2024-06-01,2024-01-16,Monday,0,31,Monday,Monday,False,False
1,102,2024-02-20,2024-06-15,2024-02-21,Tuesday,1,29,Tuesday,Tuesday,True,False
2,103,2024-03-05,2024-07-01,2024-03-06,Tuesday,1,31,Tuesday,Tuesday,True,False
3,104,2024-03-18,2024-07-08,2024-03-19,Monday,0,31,Monday,Monday,False,False
4,105,2024-04-10,2024-07-12,2024-04-11,Wednesday,2,30,Wednesday,Wednesday,False,True

In [36]:
df_dates["last_purchase"] = pd.to_datetime(df_dates["last_purchase"])

In [37]:
df_dates["last_purchase_dow"] = df_dates["last_purchase"].dt.day_of_week
df_dates

,customer_id,signup_date,last_purchase,new_day,signup-date-don,signup_date_dow,signup_date_dm,signup-date_don,signup_date_don,last_purchase_dow
0,101,2024-01-15,2024-06-01,2024-01-16,Monday,0,31,Monday,Monday,5
1,102,2024-02-20,2024-06-15,2024-02-21,Tuesday,1,29,Tuesday,Tuesday,5
2,103,2024-03-05,2024-07-01,2024-03-06,Tuesday,1,31,Tuesday,Tuesday,0
3,104,2024-03-18,2024-07-08,2024-03-19,Monday,0,31,Monday,Monday,0
4,105,2024-04-10,2024-07-12,2024-04-11,Wednesday,2,30,Wednesday,Wednesday,4

In [38]:
df_dates["last_purchase_doy"]= df_dates["last_purchase"].dt.day_of_year
df_dates

,customer_id,signup_date,last_purchase,new_day,signup-date-don,signup_date_dow,signup_date_dm,signup-date_don,signup_date_don,last_purchase_dow,last_purchase_doy
0,101,2024-01-15,2024-06-01,2024-01-16,Monday,0,31,Monday,Monday,5,153
1,102,2024-02-20,2024-06-15,2024-02-21,Tuesday,1,29,Tuesday,Tuesday,5,167
2,103,2024-03-05,2024-07-01,2024-03-06,Tuesday,1,31,Tuesday,Tuesday,0,183
3,104,2024-03-18,2024-07-08,2024-03-19,Monday,0,31,Monday,Monday,0,190
4,105,2024-04-10,2024-07-12,2024-04-11,Wednesday,2,30,Wednesday,Wednesday,4,194

In [41]:
df_dates["signup_month_sm"] = df_dates["signup_date"].dt.to_period("M").dt.start_time
df_dates["signup_month_em"] = df_dates["signup_date"].dt.to_period("M").dt.end_time
df_dates

,customer_id,signup_date,last_purchase,new_day,signup-date-don,signup_date_dow,signup_date_dm,signup-date_don,signup_date_don,last_purchase_dow,last_purchase_doy,signup_date_doy,signup_month_sm,signup_month_em
0,101,2024-01-15,2024-06-01,2024-01-16,Monday,0,31,Monday,Monday,5,153,Monday,2024-01-01,2024-01-31 23:59:59.999999
1,102,2024-02-20,2024-06-15,2024-02-21,Tuesday,1,29,Tuesday,Tuesday,5,167,Tuesday,2024-02-01,2024-02-29 23:59:59.999999
2,103,2024-03-05,2024-07-01,2024-03-06,Tuesday,1,31,Tuesday,Tuesday,0,183,Tuesday,2024-03-01,2024-03-31 23:59:59.999999
3,104,2024-03-18,2024-07-08,2024-03-19,Monday,0,31,Monday,Monday,0,190,Monday,2024-03-01,2024-03-31 23:59:59.999999
4,105,2024-04-10,2024-07-12,2024-04-11,Wednesday,2,30,Wednesday,Wednesday,4,194,Wednesday,2024-04-01,2024-04-30 23:59:59.999999

In [42]:
df_dates.sort_values("signup_date", ascending=True)

,customer_id,signup_date,last_purchase,new_day,signup-date-don,signup_date_dow,signup_date_dm,signup-date_don,signup_date_don,last_purchase_dow,last_purchase_doy,signup_date_doy,signup_month_sm,signup_month_em
0,101,2024-01-15,2024-06-01,2024-01-16,Monday,0,31,Monday,Monday,5,153,Monday,2024-01-01,2024-01-31 23:59:59.999999
1,102,2024-02-20,2024-06-15,2024-02-21,Tuesday,1,29,Tuesday,Tuesday,5,167,Tuesday,2024-02-01,2024-02-29 23:59:59.999999
2,103,2024-03-05,2024-07-01,2024-03-06,Tuesday,1,31,Tuesday,Tuesday,0,183,Tuesday,2024-03-01,2024-03-31 23:59:59.999999
3,104,2024-03-18,2024-07-08,2024-03-19,Monday,0,31,Monday,Monday,0,190,Monday,2024-03-01,2024-03-31 23:59:59.999999
4,105,2024-04-10,2024-07-12,2024-04-11,Wednesday,2,30,Wednesday,Wednesday,4,194,Wednesday,2024-04-01,2024-04-30 23:59:59.999999

In [43]:
for i in range(6):
    print(i)

0
1
2
3
4
5

In [48]:
pd.date_range(start="2026-05-14", periods=9, freq="D")

DatetimeIndex(['2026-05-14', '2026-05-15', '2026-05-16', '2026-05-17',
               '2026-05-18', '2026-05-19', '2026-05-20', '2026-05-21',
               '2026-05-22'],
              dtype='datetime64[us]', freq='D')