# Data Vizualization | Plotly

### Import Pakcages

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

## Dummy Dataset for Plotly Examples

In [2]:
np.random.seed(42)
px.defaults.template = "plotly_white"

months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])
            
df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

### Bar Plot

In [3]:
region_sales = (
    df_plotly.groupby("region", as_index=False)["sales"]
             .sum())
region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [4]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    text="sales",
    title="Total Sales by Region"
)

fig.update_traces(textposition="outside")
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales"
)

fig.show()

### Line Plot

In [5]:
monthly_sales = (
    df_plotly.groupby("month", as_index=False)["sales"]
    .sum())

monthly_sales

       month  sales
0 2024-01-01    807
1 2024-02-01    810
2 2024-03-01    831
3 2024-04-01    855
4 2024-05-01    934
5 2024-06-01    796

In [6]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales")

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales")

fig.show()

### Histogram

In [7]:
fig = px.histogram(
    df_plotly,
    x="sales",
    nbins=15,
    title="Distribution of Sales")
fig.update_layout(
        xaxis_title="Sales",
        yaxis_title="Count")
fig.show()

### Scatter Plot

In [8]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    color="region",
    title="Customers VS Sales",
    hover_data=["product", "month_name", "units"]
)

fig.update_layout(
    xaxis_title="Customers",
    yaxis_title="Sales",
    legend_title="Region"
)

fig.show()

### Multi-Line Chart

In [9]:
monthly_region_sales = (
    df_plotly.groupby(["month", "region"], as_index=False)["sales"]
    .sum())
monthly_region_sales.head()

       month region  sales
0 2024-01-01   East    217
1 2024-01-01  North    276
2 2024-01-01  South    314
3 2024-02-01   East    273
4 2024-02-01  North    305

In [10]:
fig = px.line(
    monthly_region_sales,
    x="month",
    y="sales",
    color="region",
    markers=True,
    title="Monthly Sales by Region"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales",
    legend_title="Region"
)

fig.show()

### Grouped Bar Plot

In [11]:
region_product_sales = (
    df_plotly.groupby(["region", "product"], as_index=False)["sales"]
    .sum()
)

region_product_sales

  region product  sales
0   East       A    853
1   East       B    706
2  North       A    888
3  North       B    912
4  South       A    958
5  South       B    716

In [12]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product")

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title="Product"
)

fig.show()

### Donut Chart

In [14]:
product_sales = (
    df_plotly.groupby("product", as_index=False)["sales"]
    .sum())
product_sales

  product  sales
0       A   2699
1       B   2334

In [25]:
fig = px.pie(
    product_sales,
    names="product",
    values="sales",
    hole=0.5,
    title="Share of Total Sales by Product")
fig.update_traces(textinfo="label+percent")
fig.show()

## Changing Colors in Plotly

### Single Color for the Whole Plot

In [29]:
region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [31]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region",
    color_discrete_sequence=["#07375a"])

fig.show()

### Different Colors by Category

In [36]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product",
    color_discrete_sequence=["#0A305E", "#880202"]
)

fig.show()

### Map Specific Categories to Specific Colors

In [42]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product",
    color_discrete_map={
        "A": "#011F41",
        "B": "#610000"
    })
fig.show()

### Change Line Colors

In [47]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales",
    color_discrete_sequence=["purple"])
fig.show()

### Multi-Line Colors

In [49]:
monthly_region_sales

        month region  sales
0  2024-01-01   East    217
1  2024-01-01  North    276
2  2024-01-01  South    314
3  2024-02-01   East    273
4  2024-02-01  North    305
5  2024-02-01  South    232
6  2024-03-01   East    250
7  2024-03-01  North    282
8  2024-03-01  South    299
9  2024-04-01   East    216
10 2024-04-01  North    343
11 2024-04-01  South    296
12 2024-05-01   East    350
13 2024-05-01  North    322
14 2024-05-01  South    262
15 2024-06-01   East    253
16 2024-06-01  North    272
17 2024-06-01  South    271

In [50]:
fig = px.line(
    monthly_region_sales,
    x="month",
    y="sales",
    color="region",
    markers=True,
    title="Monthly Sales by Region",
    color_discrete_map={
        "North": "#1f77b4",
        "East": "#ff7f0e",
        "South": "#2ca02c"
    })
fig.show()

### Change Histogram Colors

In [60]:
fig = px.histogram(
    df_plotly,
    x="sales",
    nbins=15,
    title="Distribution of Sales",
    color_discrete_sequence=["#654663"]
)

fig.update_layout(
    xaxis_title="Sales",
    yaxis_title="Count"
)

fig.show()

### Change Scatter Plot Colors

In [61]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    title="Customers VS Sales",
    color_discrete_sequence=["darkblue"]
)

fig.show()

## Change Colors After the Figure is Created

### Update Trace Color

In [68]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region"
)

fig.update_traces(marker_color="teal")

fig.show()

### Update Trace Color

In [71]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales"
)

fig.update_traces(line_color="red")

fig.show()

## Highlighting Only the Specific Categories

In [72]:
region_sales = (
    df_plotly.groupby("region", as_index=False)["sales"]
    .sum()
)

top_region = region_sales.loc[region_sales["sales"].idxmax(), "region"]

region_sales["highlight"] = np.where(
    region_sales["region"] == top_region,
    "Highest Sales",
    "Other Regions"
)

region_sales

  region  sales      highlight
0   East   1559  Other Regions
1  North   1800  Highest Sales
2  South   1674  Other Regions

### Creating the Bar Plot

In [87]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    color="highlight",
    text="sales",
    title="Highlighting Only the Largest Category",
    color_discrete_map={
        "Highesy Sales": "#225FA9",
        "Other Sales": "#997B7B"
    }
)

fig.update_traces(textposition="outside")

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title=""
)

fig.show()

### Highlighting the Largest Category in a Donut Chart

In [89]:
product_sales = (
    df_plotly.groupby("product", as_index=False)["sales"]
             .sum()
)

top_product = product_sales.loc[product_sales["sales"].idxmax(), "product"]

product_sales["highlight"] = np.where(
    product_sales["product"] == top_product,
    "Highest Sales",
    "Other Products"
)

product_sales

  product  sales       highlight
0       A   2699   Highest Sales
1       B   2334  Other Products

In [90]:
fig = px.pie(
    product_sales,
    names="product",
    values="sales",
    color="highlight",
    hole=0.5,
    title="Highlighting Only the Largest Category",
    color_discrete_map={
        "Highest Sales": "#3B6EAD",
        "Other Products": "#D9D9D9"
    }
)

fig.update_traces(textinfo="label+percent")

fig.show()

### Highlighting the Smallest Category in a Scatter Plot

In [91]:
region_totals = (
    df_plotly.groupby("region", as_index=False)["sales"]
             .sum()
)

top_region = region_totals.loc[region_totals["sales"].idxmin(), "region"]

df_scatter = df_plotly.copy()

df_scatter["highlight"] = np.where(
    df_scatter["region"] == top_region,
    "Highest Sales Region",
    "Other Regions"
)

df_scatter.head()

,month,region,product,sales,customers,units,month_name,highlight
0,2024-01-01,North,A,182,71,38,Jan,Other Regions
1,2024-01-01,North,B,94,80,30,Jan,Other Regions
2,2024-01-01,South,A,182,43,12,Jan,Other Regions
3,2024-01-01,South,B,132,21,33,Jan,Other Regions
4,2024-01-01,East,A,117,21,69,Jan,Highest Sales Region

In [98]:
fig = px.scatter(
    df_scatter,
    x="units",
    y="sales",
    color="highlight",
    hover_data=["region", "product", "month_name", "customers"],
    size="units",
    title="Highlighting the Largest Category",
    color_discrete_map={
        "Highest Sales Region": "#144787",
        "Other Regions": "#A35859"
    }
)

fig.update_layout(
    xaxis_title="Units",
    yaxis_title="Sales",
    legend_title=""
)

fig.show()

### Highlighting the Largest Category in a Bubble Chart

In [99]:
df_bubble = df_plotly.copy()

df_bubble["highlight"] = np.where(
    df_bubble["region"] == top_region,
    "Highest Sales Region",
    "Other Regions"
)

df_bubble.head()

,month,region,product,sales,customers,units,month_name,highlight
0,2024-01-01,North,A,182,71,38,Jan,Other Regions
1,2024-01-01,North,B,94,80,30,Jan,Other Regions
2,2024-01-01,South,A,182,43,12,Jan,Other Regions
3,2024-01-01,South,B,132,21,33,Jan,Other Regions
4,2024-01-01,East,A,117,21,69,Jan,Highest Sales Region

In [101]:
fig = px.scatter(
    df_bubble,
    x="customers",
    y="sales",
    size="customers",
    color="highlight",
    hover_data=["region", "product", "month_name"],
    title="Highlighting the Largest Category",
    color_discrete_map={
        "Highest Sales Region": "#3B6EAD",
        "Other Regions": "#D9D9D9"
    }
)

fig.update_layout(
    xaxis_title="Customers",
    yaxis_title="Sales",
    legend_title=""
)

fig.show()

### Highlighting the Largest Category in a Line Chart

In [102]:
monthly_sales = (
    df_plotly.groupby("month", as_index=False)["sales"]
             .sum()
)

max_month_row = monthly_sales.loc[monthly_sales["sales"].idxmax()]
max_month_row

month    2024-05-01 00:00:00
sales                    934
Name: 4, dtype: object

In [106]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Highlighting the Maximum Point"
)

fig.add_scatter(
    x=[max_month_row["month"]],
    y=[max_month_row["sales"]],
    marker=dict(size=14,color="#3B6EAD"),
    mode="markers",
    name="Maximum"
)

fig.show()

### Highlighting the Largest Category in a Multi-Line Chart

In [107]:
monthly_region_sales = (
    df_plotly.groupby(["month", "region"], as_index=False)["sales"]
             .sum()
)

region_totals = (
    monthly_region_sales.groupby("region", as_index=False)["sales"]
                        .sum()
)

top_region = region_totals.loc[region_totals["sales"].idxmax(), "region"]

monthly_region_sales["highlight"] = np.where(
    monthly_region_sales["region"] == top_region,
    monthly_region_sales["region"],
    "Other Regions"
)

monthly_region_sales.head()

       month region  sales      highlight
0 2024-01-01   East    217  Other Regions
1 2024-01-01  North    276          North
2 2024-01-01  South    314  Other Regions
3 2024-02-01   East    273  Other Regions
4 2024-02-01  North    305          North

In [108]:
fig = px.line(
    monthly_region_sales,
    x="month",
    y="sales",
    color="highlight",
    markers=True,
    title="Highlighting Only the Largest Category",
    color_discrete_map={
        top_region: "#3B6EAD",
        "Other Regions": "#D9D9D9"
    }
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales",
    legend_title=""
)

fig.show()

### Highlighting the Largest Category in a Histogram

In [109]:
df_hist = df_plotly.copy()

df_hist["highlight"] = np.where(
    df_hist["region"] == top_region,
    "Highest Sales Region",
    "Other Regions"
)

df_hist.head()

,month,region,product,sales,customers,units,month_name,highlight
0,2024-01-01,North,A,182,71,38,Jan,Highest Sales Region
1,2024-01-01,North,B,94,80,30,Jan,Highest Sales Region
2,2024-01-01,South,A,182,43,12,Jan,Other Regions
3,2024-01-01,South,B,132,21,33,Jan,Other Regions
4,2024-01-01,East,A,117,21,69,Jan,Other Regions

In [112]:
fig = px.histogram(
    df_hist,
    x="sales",
    color="highlight",
    barmode="overlay",
    opacity=0.7,
    title="Distribution with Highlighted Largest Category",
    color_discrete_map={
        "Highest Sales Region": "#3B6EAD",
        "Other Regions": "#D9D9D9"
    }
)

fig.update_layout(
    xaxis_title="Sales",
    yaxis_title="Count",
    legend_title=""
)

fig.show()

### Highlighting the Largest Category in a Grouped Bar Plot

In [114]:
region_product_sales = (
    df_plotly.groupby(["region", "product"], as_index=False)["sales"]
    .sum()
)

product_totals = (
    region_product_sales.groupby("product", as_index=False)["sales"]
    .sum()
)

top_product = product_totals.loc[product_totals["sales"].idxmax(), "product"]

region_product_sales["highlight"] = np.where(
    region_product_sales["product"] == top_product,
    top_product,
    "Other Products"
)

region_product_sales

  region product  sales       highlight
0   East       A    853               A
1   East       B    706  Other Products
2  North       A    888               A
3  North       B    912  Other Products
4  South       A    958               A
5  South       B    716  Other Products

In [118]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="highlight",
    barmode="group",
    title="Highlighting Only the Largest Category",
    color_discrete_map={
        top_product: "#3B6EAD",
        "Other Products": "#9D9D9D"
    }
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title=""
)

fig.show()

## Vertical and Horizontal Reference Lines

### Horizontal Lines

In [120]:
monthly_sales = (
    df_plotly.groupby("month", as_index=False)["sales"]
    .sum())
monthly_sales

       month  sales
0 2024-01-01    807
1 2024-02-01    810
2 2024-03-01    831
3 2024-04-01    855
4 2024-05-01    934
5 2024-06-01    796

In [121]:
avg_sales = monthly_sales["sales"].mean()
avg_sales

np.float64(838.8333333333334)

In [129]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Line Plot with Horizontal Reference Line")
fig.add_hline(
    y=avg_sales,
    line_dash="dot",
    annotation_text="Average Sales",
    annotation_position="top left")
fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales")
fig.show()

### Vertical Lines

In [135]:
campaign_start = pd.Timestamp("2024-04-01")

fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Line Plot with Vertical Event Line"
)

fig.add_vline(
    x=campaign_start,
    line_dash="dot",
    line_color="red"
)

fig.add_annotation(
    x=campaign_start,
    y=monthly_sales["sales"].max(),
    text="Campaign Start",
    showarrow=True,
    arrowhead=2,
    ax=40,
    ay=-40
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

### Horizontal and Vertical Lines Together

In [136]:
campaign_start = pd.Timestamp("2024-04-01")
avg_sales = monthly_sales["sales"].mean()

fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Line Plot with Horizontal and Vertical Reference Lines"
)

fig.add_hline(
    y=avg_sales,
    line_dash="dash",
    annotation_text="Average Sales",
    annotation_position="top left"
)

fig.add_vline(
    x=campaign_start,
    line_dash="dot",
    line_color="red"
)

fig.add_annotation(
    x=campaign_start,
    y=monthly_sales["sales"].max(),
    text="Campaign Start",
    showarrow=True,
    arrowhead=2,
    ax=40,
    ay=-40
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()