# DateTime

## Import Packages

In [132]:
import pandas as pd
from datetime import datetime, date, timedelta
from pandas.tseries.offsets import MonthEnd, MonthBegin

## Practice with the datetime Module

### Create a date Object

In [2]:
my_date = date(2025, 3, 15)
my_date

datetime.date(2025, 3, 15)

In [3]:
print (f"Year: {my_date.year}")
print(f"Month: {my_date.month}")
print(f"Day: {my_date.day}")
print(f"Date: {my_date}")

Year: 2025
Month: 3
Day: 15
Date: 2025-03-15

### Create a datetime Object

In [4]:
meeting_time = datetime(2025, 8, 8, 16, 45, 30)
meeting_time

datetime.datetime(2025, 8, 8, 16, 45, 30)

In [5]:
print(f"Year: {meeting_time.year}")
print(f"Month: {meeting_time.month}")
print(f"Day: {meeting_time.day}")
print(f"Hour:-> {meeting_time.hour}")
print(f"Minute:-> {meeting_time.minute}")
print(f"Second:-> {meeting_time.second}")

Year: 2025
Month: 8
Day: 8
Hour:-> 16
Minute:-> 45
Second:-> 30

### Format Dates as Strings using meeting_time

In [6]:
meeting_time.strftime("%Y/%m/%d")

'2025/08/08'

In [7]:
meeting_time.strftime("%d/%m/%Y")

'08/08/2025'

In [8]:
meeting_time.strftime("%B %d, %Y")

'August 08, 2025'

### Parse a String into a Datetime

In [9]:
dt = datetime.strptime("2025-12-31", "%Y-%m-%d")
dt

datetime.datetime(2025, 12, 31, 0, 0)

In [10]:
type(dt)

datetime.datetime

In [11]:
print(f"Date: {dt}")

Date: 2025-12-31 00:00:00

## Date Arithmetic

### Calculate the difference between `end` and `start`

In [12]:
start = date(2025, 1, 10)
end = date(2025,2,5)

In [13]:
delta = end - start
type(delta)

datetime.timedelta

In [14]:
print(type((delta).days))
delta

<class 'int'>

datetime.timedelta(days=26)

In [15]:
print(start + timedelta(days=10))
print(start - timedelta(days=14))
print(start + timedelta(weeks=3))

2025-01-20
2024-12-27
2025-01-31

In [16]:
niceday = datetime(2026, 5, 22, 12, 1, 1)

In [17]:
print(niceday + timedelta(hours=5, minutes=20, seconds=45))

2026-05-22 17:21:46

## Practice with Pandas Dates

In [18]:
df_dataframe = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5],
    "signup_date": ["2024-1-10", "2024-2-5", "2024-3-12", "2024-4-1", "2024-5-20"],
    "last_purchase": ["2024-2-15", "2024-3-01", "2024-3-28", "2024-5-10", "2024-6-25"]
})

df_dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      str
 2   last_purchase  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 340.0 bytes

In [19]:
df_dataframe.to_csv("df_dataframe.csv", index=False)

In [20]:
pd.read_csv("df_dataframe.csv")

   customer_id signup_date last_purchase
0            1   2024-1-10     2024-2-15
1            2    2024-2-5     2024-3-01
2            3   2024-3-12     2024-3-28
3            4    2024-4-1     2024-5-10
4            5   2024-5-20     2024-6-25

In [21]:
df_dataframe["signup_date"] = pd.to_datetime(df_dataframe["signup_date"])
df_dataframe["last_purchase"] = pd.to_datetime(df_dataframe["last_purchase"])

In [22]:
df_dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), int64(1)
memory usage: 252.0 bytes

### Extract Date Components

In [23]:
df_dataframe["signup_year"] = df_dataframe["signup_date"].dt.year
df_dataframe["signup_quarter"] = df_dataframe["signup_date"].dt.quarter
df_dataframe["signup_month"] = df_dataframe["signup_date"].dt.month
df_dataframe["signup_day"] = df_dataframe["signup_date"].dt.day
df_dataframe["signup_month_name"] = df_dataframe["signup_date"].dt.month_name()
df_dataframe["signup_day_name"] = df_dataframe["signup_date"].dt.day_name()

In [24]:
df_dataframe

,customer_id,signup_date,last_purchase,signup_year,signup_quarter,signup_month,signup_day,signup_month_name,signup_day_name
0,1,2024-01-10,2024-02-15,2024,1,1,10,January,Wednesday
1,2,2024-02-05,2024-03-01,2024,1,2,5,February,Monday
2,3,2024-03-12,2024-03-28,2024,1,3,12,March,Tuesday
3,4,2024-04-01,2024-05-10,2024,2,4,1,April,Monday
4,5,2024-05-20,2024-06-25,2024,2,5,20,May,Monday

In [25]:
df_dataframe["signup_dow"] = df_dataframe["signup_date"].dt.day_of_week

In [26]:
df_dataframe['is_weekend'] = df_dataframe['signup_dow'].isin([0, 6]).astype(int)

In [27]:
df_dataframe

,customer_id,signup_date,last_purchase,signup_year,signup_quarter,signup_month,signup_day,signup_month_name,signup_day_name,signup_dow,is_weekend
0,1,2024-01-10,2024-02-15,2024,1,1,10,January,Wednesday,2,0
1,2,2024-02-05,2024-03-01,2024,1,2,5,February,Monday,0,1
2,3,2024-03-12,2024-03-28,2024,1,3,12,March,Tuesday,1,0
3,4,2024-04-01,2024-05-10,2024,2,4,1,April,Monday,0,1
4,5,2024-05-20,2024-06-25,2024,2,5,20,May,Monday,0,1

In [32]:
df_dataframe["days_between_signup_and_purchase"] = (df_dataframe["last_purchase"] - df_dataframe["signup_date"]).dt.days

In [33]:
df_dataframe.head()

,customer_id,signup_date,last_purchase,signup_year,signup_quarter,signup_month,signup_day,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase
0,1,2024-01-10,2024-02-15,2024,1,1,10,January,Wednesday,2,0,36
1,2,2024-02-05,2024-03-01,2024,1,2,5,February,Monday,0,1,25
2,3,2024-03-12,2024-03-28,2024,1,3,12,March,Tuesday,1,0,16
3,4,2024-04-01,2024-05-10,2024,2,4,1,April,Monday,0,1,39
4,5,2024-05-20,2024-06-25,2024,2,5,20,May,Monday,0,1,36

### Filter Data

In [50]:
filtered_df = df_dataframe[df_dataframe["signup_date"] > "2024-03-01"].sort_values(by= "signup_date", ascending=True)
filtered_df

,customer_id,signup_date,last_purchase,signup_year,signup_quarter,signup_month,signup_day,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase
2,3,2024-03-12,2024-03-28,2024,1,3,12,March,Tuesday,1,0,16
3,4,2024-04-01,2024-05-10,2024,2,4,1,April,Monday,0,1,39
4,5,2024-05-20,2024-06-25,2024,2,5,20,May,Monday,0,1,36

In [59]:
filtered_by_march_df = df_dataframe[df_dataframe["signup_month"] == 3].sort_values(by= "signup_date", ascending=True)
filtered_by_march_df

,customer_id,signup_date,last_purchase,signup_year,signup_quarter,signup_month,signup_day,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase
2,3,2024-03-12,2024-03-28,2024,1,3,12,March,Tuesday,1,0,16

In [60]:
filtered_by_year_df = df_dataframe[df_dataframe["signup_year"] == 2024].sort_values(by= "signup_date", ascending=True)
filtered_by_year_df

,customer_id,signup_date,last_purchase,signup_year,signup_quarter,signup_month,signup_day,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase
0,1,2024-01-10,2024-02-15,2024,1,1,10,January,Wednesday,2,0,36
1,2,2024-02-05,2024-03-01,2024,1,2,5,February,Monday,0,1,25
2,3,2024-03-12,2024-03-28,2024,1,3,12,March,Tuesday,1,0,16
3,4,2024-04-01,2024-05-10,2024,2,4,1,April,Monday,0,1,39
4,5,2024-05-20,2024-06-25,2024,2,5,20,May,Monday,0,1,36

## Generate a daily date range starting from `2024-07-01` for 10 days

In [72]:
pd.date_range(start="2024-07-01", periods=10, freq="D")

DatetimeIndex(['2024-07-01', '2024-07-02', '2024-07-03', '2024-07-04',
               '2024-07-05', '2024-07-06', '2024-07-07', '2024-07-08',
               '2024-07-09', '2024-07-10'],
              dtype='datetime64[us]', freq='D')

In [76]:
pd.date_range(start="2024-01-01", periods=12, freq="MS")

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
               '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01'],
              dtype='datetime64[us]', freq='MS')

### Create a DataFrame

In [91]:
df_dataframe_1 = pd.DataFrame({
    "date": (pd.date_range(start="2024-1-1", periods=15, freq="D")),
    "sales": [90, 30, 50, 25, 220, 135, 19, 190, 70, 75, 47, 29, 30, 44, 235]
})

In [92]:
df_dataframe_1

         date  sales
0  2024-01-01     90
1  2024-01-02     30
2  2024-01-03     50
3  2024-01-04     25
4  2024-01-05    220
5  2024-01-06    135
6  2024-01-07     19
7  2024-01-08    190
8  2024-01-09     70
9  2024-01-10     75
10 2024-01-11     47
11 2024-01-12     29
12 2024-01-13     30
13 2024-01-14     44
14 2024-01-15    235

In [100]:
df_dataframe_1.to_csv('date_homework.csv',index=False)

In [103]:
df_dataframe_1 = pd.read_csv("date_homework.csv")
df_dataframe_1

          date  sales
0   2024-01-01     90
1   2024-01-02     30
2   2024-01-03     50
3   2024-01-04     25
4   2024-01-05    220
5   2024-01-06    135
6   2024-01-07     19
7   2024-01-08    190
8   2024-01-09     70
9   2024-01-10     75
10  2024-01-11     47
11  2024-01-12     29
12  2024-01-13     30
13  2024-01-14     44
14  2024-01-15    235

In [104]:
df_dataframe_1.head()

         date  sales
0  2024-01-01     90
1  2024-01-02     30
2  2024-01-03     50
3  2024-01-04     25
4  2024-01-05    220

In [128]:
df_dataframe_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    15 non-null     datetime64[s]
 1   sales   15 non-null     int64
dtypes: datetime64[s](1), int64(1)
memory usage: 372.0 bytes

In [127]:
df_dataframe_1["date"] = pd.to_datetime(df_dataframe_1["date"])

In [129]:
df_dataframe_1['year'] = df_dataframe_1['date'].dt.year
df_dataframe_1['month'] = df_dataframe_1['date'].dt.month
df_dataframe_1['day'] = df_dataframe_1['date'].dt.day
df_dataframe_1['day_name'] = df_dataframe_1['date'].dt.day_name()
df_dataframe_1['dow'] = df_dataframe_1['date'].dt.dayofweek
df_dataframe_1['is_weekend'] = df_dataframe_1['date'].dt.dayofweek.isin([5, 6]).astype(int)

In [130]:
df_dataframe_1.head()

        date  sales  year  month  day   day_name  dow  is_weekend
0 2024-01-01     90  2024      1    1     Monday    0           0
1 2024-01-02     30  2024      1    2    Tuesday    1           0
2 2024-01-03     50  2024      1    3  Wednesday    2           0
3 2024-01-04     25  2024      1    4   Thursday    3           0
4 2024-01-05    220  2024      1    5     Friday    4           0

### Beginning and End of Month

In [139]:
df_dataframe_1['month_start'] = df_dataframe_1["date"] - MonthBegin(1)

In [140]:
df_dataframe_1["month_end"] = df_dataframe_1["date"] - MonthEnd(0)

In [141]:
df_dataframe_1

,date,sales,year,month,day,day_name,dow,is_weekend,month_start,month_end
0,2024-01-01,90,2024,1,1,Monday,0,0,2023-12-01,2024-01-31
1,2024-01-02,30,2024,1,2,Tuesday,1,0,2024-01-01,2024-01-31
2,2024-01-03,50,2024,1,3,Wednesday,2,0,2024-01-01,2024-01-31
3,2024-01-04,25,2024,1,4,Thursday,3,0,2024-01-01,2024-01-31
4,2024-01-05,220,2024,1,5,Friday,4,0,2024-01-01,2024-01-31
5,2024-01-06,135,2024,1,6,Saturday,5,1,2024-01-01,2024-01-31
6,2024-01-07,19,2024,1,7,Sunday,6,1,2024-01-01,2024-01-31
7,2024-01-08,190,2024,1,8,Monday,0,0,2024-01-01,2024-01-31
8,2024-01-09,70,2024,1,9,Tuesday,1,0,2024-01-01,2024-01-31
9,2024-01-10,75,2024,1,10,Wednesday,2,0,2024-01-01,2024-01-31
10,2024-01-11,47,2024,1,11,Thursday,3,0,2024-01-01,2024-01-31
11,2024-01-12,29,2024,1,12,Friday,4,0,2024-01-01,2024-01-31
12,2024-01-13,30,2024,1,13,Saturday,5,1,2024-01-01,2024-01-31
13,2024-01-14,44,2024,1,14,Sunday,6,1,2024-01-01,2024-01-31
14,2024-01-15,235,2024,1,15,Monday,0,0,2024-01-01,2024-01-31